server:
  port: 8000

spring:
  application:
    name: exchange-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/exchange_service
    username: root
    password: ${DB_PASSWORD:FwDevJava83$}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    open-in-view: false

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

management:
  tracing:
    sampling:
      probability: 1.0
    export:
      zipkin:
        endpoint: ${MANAGEMENT_TRACING_EXPORT_ZIPKIN_ENDPOINT:${SPRING_ZIPKIN_BASEURL:http://localhost:9411}/api/v2/spans}
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  observations:
    http:
      server:
        requests:
          enabled: true

logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"

springdoc:
  api-docs:
    path: /exchange-service/v3/api-docs
  swagger-ui:
    url: /exchange-service/v3/api-docs
  override-server-url: true