server:
  port: 8761

spring:
  application:
    name: naming-server

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

management:
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411}/api/v2/spans
    base-url: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411}