services:
  naming-server:
    image: werther83/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    networks:
      - werther-network
networks:
  werther-network:
    name: fwerther-networks
    driver: bridge
