services:
  naming-server:
    image: werther83/naming-server:0.0.1-SNAPSHOT
    ports:
      - 8761:8761
    restart: always
    networks:
      - werther-network

  zipkin-server:
    image: openzipkin/zipkin:3.5.1
    ports:
      - 9411:9411
    restart: always
    networks:
      - werther-network

networks:
  werther-network:
    name: fwerther-networks
    driver: bridge
